---
- name: Ensure .ssh directory exists with secure permissions
  ansible.builtin.file:
    path: "/home/{{ user_id }}/.ssh"
    state: directory
    owner: "{{ user_id }}"
    group: "{{ user_id }}"
    mode: '0700'

- name: Add authorized key for the user
  ansible.posix.authorized_key:
    user: "{{ user_id }}"
    state: present
    key: "{{ ssh_public_key }}"
    exclusive: no

- name: Disable Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    validate: '/usr/sbin/sshd -t -f %s' # Validate config before saving!
  notify: Restart SSH

- name: Disable Root Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart SSH

- name: Disable Challenge Response (PAM)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart SSH

- name: Disable Empty Passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart SSH